# Generated by Django 4.2.7 on 2023-11-25 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userMgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='modifief_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
