# Generated by Django 4.2.7 on 2023-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0005_remove_usercontact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
