# Generated by Django 4.2.7 on 2023-11-25 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletterMgmt', '0001_initial'),
        ('userMgmt', '0002_rename_modifief_at_usercontacts_modified_at_and_more'),
        ('campaignMgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaings',
            new_name='Campaing',
        ),
    ]
