# Generated by Django 4.2.7 on 2023-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignMgmt', '0002_rename_campaings_campaing'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
