# Generated by Django 4.2.7 on 2023-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignMgmt', '0005_campaign_dynamic_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dynamic_values',
            field=models.JSONField(default=dict),
        ),
    ]
