# Generated by Django 4.2.7 on 2023-11-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0006_usercontact_status'),
        ('campaignMgmt', '0006_alter_campaign_dynamic_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CampaignSendStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignMgmt.campaign')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userMgmt.usercontact')),
            ],
        ),
    ]
