# Generated by Django 4.2.7 on 2023-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettertemplate',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
